// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api-ai/ent/addresses"
	"api-ai/ent/contacts"
	"api-ai/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AddressesQuery is the builder for querying Addresses entities.
type AddressesQuery struct {
	config
	ctx         *QueryContext
	order       []addresses.OrderOption
	inters      []Interceptor
	predicates  []predicate.Addresses
	withContact *ContactsQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AddressesQuery builder.
func (aq *AddressesQuery) Where(ps ...predicate.Addresses) *AddressesQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit the number of records to be returned by this query.
func (aq *AddressesQuery) Limit(limit int) *AddressesQuery {
	aq.ctx.Limit = &limit
	return aq
}

// Offset to start from.
func (aq *AddressesQuery) Offset(offset int) *AddressesQuery {
	aq.ctx.Offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *AddressesQuery) Unique(unique bool) *AddressesQuery {
	aq.ctx.Unique = &unique
	return aq
}

// Order specifies how the records should be ordered.
func (aq *AddressesQuery) Order(o ...addresses.OrderOption) *AddressesQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryContact chains the current query on the "contact" edge.
func (aq *AddressesQuery) QueryContact() *ContactsQuery {
	query := (&ContactsClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(addresses.Table, addresses.FieldID, selector),
			sqlgraph.To(contacts.Table, contacts.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, addresses.ContactTable, addresses.ContactColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Addresses entity from the query.
// Returns a *NotFoundError when no Addresses was found.
func (aq *AddressesQuery) First(ctx context.Context) (*Addresses, error) {
	nodes, err := aq.Limit(1).All(setContextOp(ctx, aq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{addresses.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *AddressesQuery) FirstX(ctx context.Context) *Addresses {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Addresses ID from the query.
// Returns a *NotFoundError when no Addresses ID was found.
func (aq *AddressesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aq.Limit(1).IDs(setContextOp(ctx, aq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{addresses.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *AddressesQuery) FirstIDX(ctx context.Context) int {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Addresses entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Addresses entity is found.
// Returns a *NotFoundError when no Addresses entities are found.
func (aq *AddressesQuery) Only(ctx context.Context) (*Addresses, error) {
	nodes, err := aq.Limit(2).All(setContextOp(ctx, aq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{addresses.Label}
	default:
		return nil, &NotSingularError{addresses.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *AddressesQuery) OnlyX(ctx context.Context) *Addresses {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Addresses ID in the query.
// Returns a *NotSingularError when more than one Addresses ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *AddressesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aq.Limit(2).IDs(setContextOp(ctx, aq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{addresses.Label}
	default:
		err = &NotSingularError{addresses.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *AddressesQuery) OnlyIDX(ctx context.Context) int {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AddressesSlice.
func (aq *AddressesQuery) All(ctx context.Context) ([]*Addresses, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryAll)
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Addresses, *AddressesQuery]()
	return withInterceptors[[]*Addresses](ctx, aq, qr, aq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aq *AddressesQuery) AllX(ctx context.Context) []*Addresses {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Addresses IDs.
func (aq *AddressesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if aq.ctx.Unique == nil && aq.path != nil {
		aq.Unique(true)
	}
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryIDs)
	if err = aq.Select(addresses.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *AddressesQuery) IDsX(ctx context.Context) []int {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *AddressesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryCount)
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aq, querierCount[*AddressesQuery](), aq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aq *AddressesQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *AddressesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryExist)
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *AddressesQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AddressesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *AddressesQuery) Clone() *AddressesQuery {
	if aq == nil {
		return nil
	}
	return &AddressesQuery{
		config:      aq.config,
		ctx:         aq.ctx.Clone(),
		order:       append([]addresses.OrderOption{}, aq.order...),
		inters:      append([]Interceptor{}, aq.inters...),
		predicates:  append([]predicate.Addresses{}, aq.predicates...),
		withContact: aq.withContact.Clone(),
		// clone intermediate query.
		sql:  aq.sql.Clone(),
		path: aq.path,
	}
}

// WithContact tells the query-builder to eager-load the nodes that are connected to
// the "contact" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AddressesQuery) WithContact(opts ...func(*ContactsQuery)) *AddressesQuery {
	query := (&ContactsClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withContact = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StreetName string `json:"street_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Addresses.Query().
//		GroupBy(addresses.FieldStreetName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *AddressesQuery) GroupBy(field string, fields ...string) *AddressesGroupBy {
	aq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AddressesGroupBy{build: aq}
	grbuild.flds = &aq.ctx.Fields
	grbuild.label = addresses.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StreetName string `json:"street_name,omitempty"`
//	}
//
//	client.Addresses.Query().
//		Select(addresses.FieldStreetName).
//		Scan(ctx, &v)
func (aq *AddressesQuery) Select(fields ...string) *AddressesSelect {
	aq.ctx.Fields = append(aq.ctx.Fields, fields...)
	sbuild := &AddressesSelect{AddressesQuery: aq}
	sbuild.label = addresses.Label
	sbuild.flds, sbuild.scan = &aq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AddressesSelect configured with the given aggregations.
func (aq *AddressesQuery) Aggregate(fns ...AggregateFunc) *AddressesSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *AddressesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aq); err != nil {
				return err
			}
		}
	}
	for _, f := range aq.ctx.Fields {
		if !addresses.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *AddressesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Addresses, error) {
	var (
		nodes       = []*Addresses{}
		withFKs     = aq.withFKs
		_spec       = aq.querySpec()
		loadedTypes = [1]bool{
			aq.withContact != nil,
		}
	)
	if aq.withContact != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, addresses.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Addresses).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Addresses{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withContact; query != nil {
		if err := aq.loadContact(ctx, query, nodes, nil,
			func(n *Addresses, e *Contacts) { n.Edges.Contact = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *AddressesQuery) loadContact(ctx context.Context, query *ContactsQuery, nodes []*Addresses, init func(*Addresses), assign func(*Addresses, *Contacts)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Addresses)
	for i := range nodes {
		if nodes[i].contacts_addresses == nil {
			continue
		}
		fk := *nodes[i].contacts_addresses
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(contacts.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "contacts_addresses" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (aq *AddressesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	_spec.Node.Columns = aq.ctx.Fields
	if len(aq.ctx.Fields) > 0 {
		_spec.Unique = aq.ctx.Unique != nil && *aq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *AddressesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(addresses.Table, addresses.Columns, sqlgraph.NewFieldSpec(addresses.FieldID, field.TypeInt))
	_spec.From = aq.sql
	if unique := aq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aq.path != nil {
		_spec.Unique = true
	}
	if fields := aq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, addresses.FieldID)
		for i := range fields {
			if fields[i] != addresses.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *AddressesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(addresses.Table)
	columns := aq.ctx.Fields
	if len(columns) == 0 {
		columns = addresses.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.ctx.Unique != nil && *aq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AddressesGroupBy is the group-by builder for Addresses entities.
type AddressesGroupBy struct {
	selector
	build *AddressesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *AddressesGroupBy) Aggregate(fns ...AggregateFunc) *AddressesGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the selector query and scans the result into the given value.
func (agb *AddressesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agb.build.ctx, ent.OpQueryGroupBy)
	if err := agb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AddressesQuery, *AddressesGroupBy](ctx, agb.build, agb, agb.build.inters, v)
}

func (agb *AddressesGroupBy) sqlScan(ctx context.Context, root *AddressesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*agb.flds)+len(agb.fns))
		for _, f := range *agb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*agb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AddressesSelect is the builder for selecting fields of Addresses entities.
type AddressesSelect struct {
	*AddressesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *AddressesSelect) Aggregate(fns ...AggregateFunc) *AddressesSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *AddressesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, as.ctx, ent.OpQuerySelect)
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AddressesQuery, *AddressesSelect](ctx, as.AddressesQuery, as, as.inters, v)
}

func (as *AddressesSelect) sqlScan(ctx context.Context, root *AddressesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
