// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api-ai/ent/addresses"
	"api-ai/ent/contacts"
	"api-ai/ent/files"
	"api-ai/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	addressesFields := schema.Addresses{}.Fields()
	_ = addressesFields
	// addressesDescInvoiceAddress is the schema descriptor for invoice_address field.
	addressesDescInvoiceAddress := addressesFields[5].Descriptor()
	// addresses.DefaultInvoiceAddress holds the default value on creation for the invoice_address field.
	addresses.DefaultInvoiceAddress = addressesDescInvoiceAddress.Default.(bool)
	// addressesDescServiceAddress is the schema descriptor for service_address field.
	addressesDescServiceAddress := addressesFields[6].Descriptor()
	// addresses.DefaultServiceAddress holds the default value on creation for the service_address field.
	addresses.DefaultServiceAddress = addressesDescServiceAddress.Default.(bool)
	// addressesDescCreatedAt is the schema descriptor for created_at field.
	addressesDescCreatedAt := addressesFields[7].Descriptor()
	// addresses.DefaultCreatedAt holds the default value on creation for the created_at field.
	addresses.DefaultCreatedAt = addressesDescCreatedAt.Default.(func() time.Time)
	contactsFields := schema.Contacts{}.Fields()
	_ = contactsFields
	// contactsDescCreatedAt is the schema descriptor for created_at field.
	contactsDescCreatedAt := contactsFields[5].Descriptor()
	// contacts.DefaultCreatedAt holds the default value on creation for the created_at field.
	contacts.DefaultCreatedAt = contactsDescCreatedAt.Default.(func() time.Time)
	filesFields := schema.Files{}.Fields()
	_ = filesFields
	// filesDescCreatedAt is the schema descriptor for created_at field.
	filesDescCreatedAt := filesFields[4].Descriptor()
	// files.DefaultCreatedAt holds the default value on creation for the created_at field.
	files.DefaultCreatedAt = filesDescCreatedAt.Default.(func() time.Time)
}
