definitions:
  models.ErrorResponse:
    properties:
      error:
        example: invalid credentials
        type: string
    type: object
  models.LoginRequest:
    properties:
      password:
        example: pass123
        type: string
      username:
        example: user1
        type: string
    type: object
  models.TokenResponse:
    properties:
      token:
        example: your.jwt.token
        type: string
    type: object
info:
  contact: {}
paths:
  /api/upload:
    post:
      consumes:
      - multipart/form-data
      description: Accepts a PDF file and an optional prompt for processing
      parameters:
      - description: PDF file to upload
        in: formData
        name: pdf
        required: true
        type: file
      - description: Optional processing prompt
        in: formData
        name: prompt
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: PDF uploaded
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Upload a PDF file with a prompt
      tags:
      - api
  /auth/login:
    post:
      consumes:
      - application/json
      description: Takes a username and password and returns a JWT token if valid
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TokenResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Authenticate user and return JWT token
      tags:
      - auth
  /health:
    get:
      description: Returns 200 if the service is up
      responses:
        "200":
          description: OK
      summary: Health check
      tags:
      - system
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
