// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Addresses is the predicate function for addresses builders.
type Addresses func(*sql.Selector)

// Contacts is the predicate function for contacts builders.
type Contacts func(*sql.Selector)

// Files is the predicate function for files builders.
type Files func(*sql.Selector)
